M48
; DRILL file {KiCad (6.0.7)} date Tue Oct  4 23:41:00 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-04T23:41:00+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X4.4291Y-1.4075
X4.4291Y-4.1043
X5.8071Y-1.4075
X5.8071Y-4.1043
T0
M30
